import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeWrapper from '@/app/components/wrapper/themeWrapper'
import Sidebar from '@/app/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <ThemeWrapper enableSystem={false} attribute='class'>
                <main className='flex'>
                    <Sidebar/>
                    {children}
                </main>
            </ThemeWrapper>
        </body>
    </html>
  )
}
